### ISSUE TITLE
Error running job after upgrade HA to 2024.7

### ISSUE THREAD

**Issue by maniakum** [enkama/hass-variables#120]
`Logger: homeassistant.core
Zdroj: core.py:1559
První výskyt: 11:32:01 (2865 výskyty)
Naposledy logováno: 11:34:38

Error running job: <Job listen * HassJobType.Callback <function Recorder.async_initialize.<locals>._event_listener at 0xffff9a36a700>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1559, in async_fire_internal
    self._hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 938, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 330, in _event_listener
    if entity_filter(entity_id):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/variable/recorder_history_prefilter/recorder_prefilter.py", line 134, in entity_filter
    return recorder_entity_filter(entity_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
`

**Comment by maniakum** [comment]
Remove and download again helped.

**Comment by Snuffy2** [comment]
This is the same issue as https://github.com/gcobb321/icloud3/issues/349

Once @gcobb321 resolves the issue, I'll implement the updated code here.
