### ISSUE TITLE
AttributeError: 'VariableNoRecorder' object has no attribute 'disable_recorder'

### ISSUE THREAD

**Issue by danielbrunt57** [enkama/hass-variables#125]
```
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:364
integration: Binary sensor (documentation, issues)
First occurred: 7:34:02 PM (1 occurrences)
Last logged: 7:34:02 PM

Error while setting up variable platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/variable/binary_sensor.py", line 111, in async_setup_entry
    async_add_entities([VariableNoRecorder(hass, config, config_entry, unique_id)])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/variable/binary_sensor.py", line 177, in __init__
    self.disable_recorder()
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'VariableNoRecorder' object has no attribute 'disable_recorder'. Did you mean: '_disabled_reported'?
```
binary_sensor.py
Lines 176-177
```
        if self._exclude_from_recorder:
            self.disable_recorder()
```
disable_recorder is not defined.

**Comment by danielbrunt57** [comment]
The code was there at this point:
![image](https://github.com/enkama/hass-variables/assets/49846893/c147661d-0451-41f9-9ab3-8dcd0489de43)
```
        _LOGGER.debug(f"({self._attr_name}) [init] entity_id: {self.entity_id}")
        if self._exclude_from_recorder:
            self.disable_recorder()

    def disable_recorder(self):
        if RECORDER_INSTANCE in self._hass.data:
            _LOGGER.info(f"({self._attr_name}) [disable_recorder] Disabling Recorder")
            recorder_prefilter.add_filter(self._hass, self.entity_id)
```
but disappeared here:
![image](https://github.com/enkama/hass-variables/assets/49846893/add8052e-8835-4b0c-bd2f-871b05106966)

**Comment by danielbrunt57** [comment]
I tried adding that definition:
![image](https://github.com/enkama/hass-variables/assets/49846893/daf38453-a439-42db-85e4-bdc62b13c831)

But a new error is thrown:
```
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:364
integration: Binary sensor (documentation, issues)
First occurred: 7:52:03 PM (1 occurrences)
Last logged: 7:52:03 PM

Error while setting up variable platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/variable/binary_sensor.py", line 111, in async_setup_entry
    async_add_entities([VariableNoRecorder(hass, config, config_entry, unique_id)])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/variable/binary_sensor.py", line 177, in __init__
    self.disable_recorder()
  File "/config/custom_components/variable/binary_sensor.py", line 180, in disable_recorder
    if RECORDER_INSTANCE in self._hass.data:
       ^^^^^^^^^^^^^^^^^
NameError: name 'RECORDER_INSTANCE' is not defined
```

**Comment by danielbrunt57** [comment]
Thanks!  That's the same fix that I decided to try...
```
        _LOGGER.debug(f"({self._attr_name}) [init] entity_id: {self.entity_id}")
#        if self._exclude_from_recorder:
#            self.disable_recorder()

    async def async_added_to_hass(self):
```

**Comment by Snuffy2** [comment]
Sorry, I missed those 2 lines when I was quickly fixing the issues caused by Variables in 2024.7 in #121 . 

For now, you can just delete lines 176-177 in binary_sensor.py:
```
        if self._exclude_from_recorder:
            self.disable_recorder()
```

**Comment by danielbrunt57** [comment]
Yes, I've already done that.
Thanks again for the quick response!
