### ISSUE TITLE
Unknown error occurred when editing variable

### ISSUE THREAD

**Issue by majkers** [enkama/hass-variables#131]
I use 3.4.7 version. I have two errors:

1. I create a sensor variable like this:
![image](https://github.com/user-attachments/assets/bc732b59-1810-4d1e-8a35-1a6c4e86a0c3)
After some time I try to change one of attributes by:
![image](https://github.com/user-attachments/assets/00dd53fe-4fc5-48e1-922a-913f1414c323)
option. I click save and then after HA restart I get old attribute value restored even though I have it set not to restore:
![image](https://github.com/user-attachments/assets/11d4127a-3311-47ef-b1a1-d48d0a78de41)

2. When I try to change attribute by second step of  
![image](https://github.com/user-attachments/assets/8ae0edd8-1406-4d95-b5bd-77bc348cec6c)
option like this:
![image](https://github.com/user-attachments/assets/91e78cc0-7835-4bac-b588-6b49ed9ce543)
- I don't see value
- When I add value and change attribute like this I get:
![image](https://github.com/user-attachments/assets/c8a5c13f-c861-4326-a39c-e3a6ebef758e)

And in logs:

```
Rejestrator: aiohttp.server
Źródło: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
Pierwsze zdarzenie: 12:19:29 (20 zdarzenia)
Ostatnio zalogowany: 12:29:48

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 285, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 415, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 518, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/variable/config_flow.py", line 1168, in async_step_sensor_options_page_2
    and self.add_sensor_input.get(CONF_VALUE_TYPE) == "datetime"
        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'VariableOptionsFlowHandler' object has no attribute 'add_sensor_input'
```

**Comment by Snuffy2** [comment]
If I understand correctly, "Error 1," is functioning as expected. If you don't "Restore on Restart" then every time you restart HA it will revert back to the initial Value and Attributes you have set when creating the Variable.

I'll submit a PR shortly to fix Error 2.

**Comment by majkers** [comment]
Ad Error 1. oooohhhh sorry I thought 'restore on restart' means 'restore to initial value after restart'. Sorry
